addSbtPlugin("com.github.sbt" % "sbt-pgp"       % "2.1.2")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"  % "2.4.6")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"  % "0.9.34")
addSbtPlugin("org.scoverage"  % "sbt-scoverage" % "1.9.3")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype"  % "3.9.10")
